language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
env:
  - NODE_PATH='src/'
stages:
  - test
  - build
before_install:
  - 'nvm install-latest-npm'
install:
  - npm i
jobs:
  include:
    - stage: test
      script:
        - npm run test:all
    - stage: build
      script:
        - npm run build
